version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ufficio-brevetti-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ufficio_brevetti
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    container_name: ufficio-brevetti-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/admin?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network

  backend:
    # Sostituisci con il tuo username DockerHub e il nome dell'immagine
    image: gianlucamazzeo/ufficio-brevetti-backend:91c69534
    container_name: ufficio-brevetti-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password@mongodb:27017/ufficio_brevetti?authSource=admin
      JWT_SECRET: your_jwt_secret_key_here
      JWT_EXPIRATION: 1d
      JWT_REFRESH_SECRET: your_jwt_refresh_secret_key_here
      JWT_REFRESH_EXPIRATION: 7d
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge