export enum StatoBrevetto {
    DEPOSITO = 'DEPOSITO',
    ESAME = 'ESAME',
    CONCESSIONE = 'CONCESSIONE',
    ATTIVO = 'ATTIVO',
    SCADUTO = 'SCADUTO',
    DECADUTO = 'DECADUTO',
    RINUNCIATO = 'RINUNCIATO',
    ANNULLATO = 'ANNULLATO'
  }